# Generated by Django 4.1 on 2023-12-21 01:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2023, 12, 20, 17, 56, 56, 365456)
            ),
        ),
    ]
