# Generated by Django 4.1 on 2024-01-03 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_alter_post_create_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ipynb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_data", models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="file_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 3, 15, 48, 36, 750603)
            ),
        ),
    ]
