# Generated by Django 4.1 on 2024-01-03 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_ipynb_post_file_name_alter_post_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 3, 15, 54, 2, 780965)
            ),
        ),
    ]
