# Generated by Django 4.1 on 2024-01-03 23:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0005_alter_post_create_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ipynb",
        ),
        migrations.RemoveField(
            model_name="post",
            name="file_name",
        ),
        migrations.AddField(
            model_name="post",
            name="file_data",
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 3, 15, 57, 8, 311235)
            ),
        ),
    ]
