# Generated by Django 4.1 on 2024-01-04 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_delete_ipynb_remove_post_file_name_post_file_data_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaveFileField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("save_file", models.FileField(upload_to="")),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 3, 22, 26, 44, 479890)
            ),
        ),
    ]
