# Generated by Django 4.1 on 2024-01-04 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0008_alter_post_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="create_at",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime(2024, 1, 3, 22, 35, 1, 161319)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="file_data",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
